import './globals.css'
import type { Metadata } from 'next'
import {Montserrat} from 'next/font/google'
import TextBannerComponent from "@/components/banner/textBanner";
import HeaderComponent from "@/components/layouts/header";

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Commercio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
      <div className="bg-[#252B42]">
      <TextBannerComponent />
          <HeaderComponent />
      </div>
      {children}

      </body>
    </html>
  )
}
